import logging
from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from schema import RecipeRequest, Recipe, SwapRequest, SwapResponse
from llm import generate_recipe_llm, suggest_swap_llm

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="Fridge-to-Recipe API",
    description="Backend API for generating structured recipes and swaps using Groq LLM",
    version="1.0.0"
)

# CORS configuration to allow local Vite frontend access
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # For development; in production restrict this to the frontend URL
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.post("/api/recipe", response_model=Recipe)
def create_recipe(request: RecipeRequest):
    ingredients_input = request.ingredients.strip()
    
    # Input validation
    if not ingredients_input:
        logger.warning("Empty ingredients input received.")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Ingredients list cannot be empty."
        )
    
    if len(ingredients_input) > 500:
        logger.warning("Excessively long ingredients input received.")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Ingredients description is too long (maximum 500 characters)."
        )

    logger.info(f"Generating recipe for input: '{ingredients_input}'")
    
    # Call the LLM layer
    recipe_dict = generate_recipe_llm(ingredients_input)
    
    try:
        # Validate dictionary against the Pydantic Recipe model
        validated_recipe = Recipe(**recipe_dict)
        return validated_recipe
    except Exception as e:
        logger.error(f"Recipe validation failed on backend. Recipe dict: {recipe_dict}. Error: {e}")
        # Return 422 if LLM returned wrong schema structure
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="The recipe generated by the AI did not match the required schema. Please try again."
        )

@app.post("/api/swap", response_model=SwapResponse)
def suggest_swap(request: SwapRequest):
    ingredient_name = request.ingredientName.strip()
    recipe_title = request.recipeTitle.strip()
    
    if not ingredient_name:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Ingredient name cannot be empty."
        )
        
    logger.info(f"Generating swaps for '{ingredient_name}' in recipe '{recipe_title}'")
    alternatives = suggest_swap_llm(ingredient_name, recipe_title)
    
    return SwapResponse(alternatives=alternatives)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
